src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation\Timestampable;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article implements \JsonSerializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank()
     * @var string
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @Assert\NotBlank()
     * @Assert\Length(
     *     max="255",
     *     min="2",
     *     maxMessage="Title must contain maximum 255 characters.",
     *     minMessage="Title must contain minimum 2 characters."
     * )
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @Assert\NotBlank()
     * @var string
     * @ORM\Column(type="text")
     */
    private $short_text;

    /**
     * @Assert\NotBlank()
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @Assert\NotBlank()
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="articles")
     */
    private $tag;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="article", cascade={"persist", "remove"})
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Likes", mappedBy="article", cascade={"persist", "remove"})
     */
    private $likes;

    /**
     * @var \DateTime $created
     * @Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @var \DateTime $updated
     * @Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated;

    /**
     * @Assert\Image(
     *     mimeTypes={"image/png", "image/jpg", "image/jpeg"},
     *     mimeTypesMessage = "Please upload a valid PNG, JPG or JPEG",
     *     maxSize="3000k",
     *     maxSizeMessage="Max size of the photo 3000 k",
     *     minHeight="300",
     *     minHeightMessage="Min height 300 px",
     *     minWidth="300",
     *     minWidthMessage="Min width 300 px"
     * )
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Complaint", mappedBy="article", cascade={"persist", "remove"})
     */
    private $complaints;

    public function __construct()
    {
        $this->tag = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->complaints = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getShortText(): ?string
    {
        return $this->short_text;
    }

    public function setShortText(string $short_text): self
    {
        $this->short_text = $short_text;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTag(): Collection
    {
        return $this->tag;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tag->contains($tag)) {
            $this->tag[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tag->contains($tag)) {
            $this->tag->removeElement($tag);
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Likes[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Likes $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setArticle($this);
        }

        return $this;
    }

    public function removeLike(Likes $like): self
    {
        if ($this->likes->contains($like)) {
            $this->likes->removeElement($like);
            // set the owning side to null (unless already changed)
            if ($like->getArticle() === $this) {
                $like->setArticle(null);
            }
        }

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getUpdated(): ?\DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(\DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    /**
     * @return Collection|Complaint[]
     */
    public function getComplaints(): Collection
    {
        return $this->complaints;
    }

    public function addComplaint(Complaint $complaint): self
    {
        if (!$this->complaints->contains($complaint)) {
            $this->complaints[] = $complaint;
            $complaint->setArticle($this);
        }

        return $this;
    }

    public function removeComplaint(Complaint $complaint): self
    {
        if ($this->complaints->contains($complaint)) {
            $this->complaints->removeElement($complaint);
            // set the owning side to null (unless already changed)
            if ($complaint->getArticle() === $this) {
                $complaint->setArticle(null);
            }
        }

        return $this;
    }

    public function jsonSerialize()
    {
        return [
            'id' => $this->getId(),
            'title' => $this->getTitle(),
            'short_text' => $this->getShortText(),
            'text' => $this->getText(),
            'picture' => $this->getPicture(),
            'category' => $this->getCategory(),
            'tags' => $this->getTag(),
            'created' => $this->getCreated(),
            'updated' => $this->getUpdated(),
            'author' => $this->getAuthor()
        ];
    }
}

src/Entity/Profile.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProfileRepository")
 */
class Profile implements \JsonSerializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(max="255", maxMessage="About must contain maximum 255 characters.")
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $about;

    /**
     * @Assert\NotBlank(message="Please, select the photo.")
     * @Assert\Image(
     *     mimeTypes={"image/png", "image/jpg", "image/jpeg"},
     *     mimeTypesMessage = "Please upload a valid PNG, JPG or JPEG",
     *     maxSize="3000k",
     *     maxSizeMessage="Max size of the photo 3000 k",
     *     minHeight="300",
     *     minHeightMessage="Min height 300 px",
     *     minWidth="300",
     *     minWidthMessage="Min width 300 px"
     * )
     * @ORM\Column(type="string")
     */
    private $picture;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAbout(): ?string
    {
        return $this->about;
    }

    public function setAbout(string $about): self
    {
        $this->about = $about;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function jsonSerialize()
    {
        return [
            'id' => $this->getId(),
            'about' => $this->getAbout(),
            'picture' => $this->getPicture()
        ];
    }
}

src/Form/ProfileType.php
<?php

namespace App\Form;


use App\Entity\Profile;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProfileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('about', TextType::class, [
                'attr' => [
                    'class' => 'form-control form-group',
                    'maxlength' => 255
                ],
                'empty_data' => ''
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Profile::class
        ]);
    }
}

src/Controller/Api/UserController.php
<?php

namespace App\Controller\Api;

use App\Entity\Profile;
use App\Entity\User;
use App\Services\UserService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class UserController extends AbstractController
{
    /**
     * @Route("/api/registration", methods={"POST"})
     */
    public function registrationAction(Request $request, SerializerInterface $serializer, ValidatorInterface $validator, UserService $userService)
    {
        if (!$request->getContent()) {
            throw new HttpException('400', 'Bad request');
        }

        $user = $serializer->deserialize($request->getContent(), User::class, JsonEncoder::FORMAT);

        if (count($validator->validate($user))) {
            throw new HttpException('400', 'Bad request');
        }

        $user->setApiToken($userService->generateApiToken());

        $profile = new Profile();
        $profile->setPicture('/images/profile/default_picture.png');
        $user->setProfile($profile);

        $em = $this->getDoctrine()->getManager();
        $em->persist($user);
        $em->flush();

        $userService->sendRegistrationEmail($user);

        return $this->json($user);
    }

    /**
     * @Route("/api/login", methods={"POST"})
     */
    public function loginAction(Request $request, UserPasswordEncoderInterface $passwordEncoder, UserService $userService)
    {
        if (!$request->getContent()) {
            throw new HttpException('400', 'Bad request');
        }

        $data = json_decode($request->getContent(), true);

        if (!array_key_exists('email', $data) || !array_key_exists('password', $data)) {
            throw new HttpException('400', 'Bad request');
        }

        $user = $this->getDoctrine()->getRepository(User::class)->findOneBy(['email' => $data['email']]);
        $user->setApiToken($userService->generateApiToken());

        $em = $this->getDoctrine()->getManager();
        $em->persist($user);
        $em->flush();

        if ($user instanceof User) {
            if ($passwordEncoder->isPasswordValid($user, $data['password'])) {
                return $this->json($user);
            }
        }

        throw new HttpException('400', 'Bad request');
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Profile;
use App\Entity\User;
use App\Form\LoginType;
use App\Form\RegistrationType;
use App\Services\UserService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class UserController extends AbstractController
{
    /**
     * @Route("/login", name="app_login")
     * @param AuthenticationUtils $authenticationUtils
     * @return Response
     */
    public function loginAction(AuthenticationUtils $authenticationUtils): Response
    {
        if (!$this->getUser()) {
            $error = $authenticationUtils->getLastAuthenticationError();

            $lastUsername = $authenticationUtils->getLastUsername();

            $form = $this->createForm(LoginType::class, null, ['lastUsername' => $lastUsername]);

            return $this->render('user/user/login.html.twig', [
                'error' => $error,
                'form' => $form->createView()
            ]);
        }

        return $this->redirectToRoute('app_profile_view', [
            'id' => $this->getUser()->getId()
        ]);
    }

    /**
     * @Route("/registration", name="app_registration")
     * @param Request $request
     * @return Response
     */
    public function registrationAction(Request $request, UserService $userService)
    {
        if (!$this->getUser()) {
            $user = new User();
            $profile = new Profile();
            $profile->setPicture('/images/profile/default_picture.png');
            $user->setProfile($profile);

            $form = $this->createForm(RegistrationType::class, $user);

            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $em->persist($user);
                $em->flush();

                $userService->sendRegistrationEmail($user);

                return $this->redirectToRoute('app_login');
            }

            return $this->render('user/user/registration.html.twig', [
                'form' => $form->createView()
            ]);
        }

        return $this->redirectToRoute('app_profile_view', [
            'id' => $this->getUser()->getId()
        ]);
    }
}

templates/user/profile/articles.html.twig
{% extends 'user/base.html.twig' %}

{% block title %}Symfony Blog - {{ author.firstName }} {{ author.lastName }} - My articles{% endblock %}

{% block body %}
    <div class="row">
        {{ include('user/breadcrumb.html.twig', { 'crumb': 'Profile', 'active': 'My articles' }) }}
        <div class="panel panel-default panel-article">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-book"></span>&nbsp;&nbsp;My articles</h3>
            </div>
            {% if author.articles and author.articles|length > 0 %}
                {% for article in author.articles %}
                    <div class="panel-body">
                        <p><b><a href="{{ path('app_article_view', {'id': article.id}) }}">{{ article.title }}</a></b></p>
                        <p>{{ article.shortText }}</p>
                        <p>
                            <span class="glyphicon glyphicon-heart"></span>&nbsp;&nbsp;{{ article.likes.count }}
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-comment"></span>&nbsp;&nbsp;{{ article.comments.count }}
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-tags"></span>&nbsp;&nbsp;{{ article.tag.count }}
                            <span class="pull-right">
                                <span class="glyphicon glyphicon-calendar"></span>&nbsp;&nbsp;{{ article.created|date }}
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <a href="{{ path('app_article_view', {'id': article.id}) }}" class="read_more" data-toggle="tooltip" title="Read more"><span class="glyphicon glyphicon-option-horizontal"></span></a>
                            </span>
                        </p>
                    </div>
                    <hr>
                {% endfor %}
            {% else %}
                <div class="panel-body">
                    <p class="text-center">(No articles)</p>
                </div>
            {% endif %}
            <div class="panel-body">
                <a href="{{ path('app_profile_view', {'id': author.id}) }}" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Back</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/profile/change-password.html.twig
{% extends 'user/base.html.twig' %}

{% block title %}Symfony Blog - Profile - Change password{% endblock %}

{% block body %}
    <div class="row">
        {{ include('user/breadcrumb.html.twig', { 'crumb': 'Profile', 'active': 'Change password' }) }}
        <div class="panel panel-default panel-article">
            <div class="panel-body">
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <div class="row">
                    <div class="col-md-6 col-xs-6 text-left">
                        <a href="{{ path('app_profile_view', {'id': author.id}) }}" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Back</a>
                    </div>
                    <div class="col-md-6 col-xs-6 text-right">
                        <button class="btn btn-default pull-right" type="submit"><span class="glyphicon glyphicon-ok"></span>&nbsp;&nbsp;Change</button>
                    </div>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/profile/change-picture.html.twig
{% extends 'user/base.html.twig' %}

{% block title %}Symfony Blog - Profile - Change photo{% endblock %}

{% block body %}
    <div class="row">
        {{ include('user/breadcrumb.html.twig', { 'crumb': 'Profile', 'active': 'Change photo' }) }}
        <div class="panel panel-default panel-article">
            <div class="panel-body">
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <div class="row">
                    <div class="col-md-4 col-xs-4 text-left">
                        <a href="{{ path('app_profile_view', {'id': author.id}) }}" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Back</a>
                    </div>
                    <div class="col-md-4 col-xs-4 text-center">
                        {% if author.profile.picture != '/images/profile/default_picture.png' %}
                            <a href="{{ path('app_profile_deletepicture', {'id': author.id}) }}" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span>&nbsp;&nbsp;Delete</a>
                        {% endif %}
                    </div>
                    <div class="col-md-4 col-xs-4 text-right">
                        <button class="btn btn-default pull-right" type="submit"><span class="glyphicon glyphicon-ok"></span>&nbsp;&nbsp;Upload</button>
                    </div>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/profile/comments.html.twig
{% extends 'user/base.html.twig' %}

{% block title %}Symfony Blog - {{ author.firstName }} {{ author.lastName }} - Commented articles{% endblock %}

{% block body %}
    <div class="row">
        {{ include('user/breadcrumb.html.twig', { 'crumb': 'Profile', 'active': 'Commented articles' }) }}
        <div class="panel panel-default panel-article">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-book"></span>&nbsp;&nbsp;Commented articles</h3>
            </div>
            {% if author.comments and author.comments|length > 0 %}
                {% for comment in author.comments %}
                    <div class="panel-body">
                        <p><b><a href="{{ path('app_article_view', {'id': comment.article.id}) }}">{{ comment.article.title }}</a></b></p>
                        <p>{{ comment.article.shortText }}</p>
                        <p>
                            <span class="glyphicon glyphicon-heart"></span>&nbsp;&nbsp;{{ comment.article.likes.count }}
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-comment"></span>&nbsp;&nbsp;{{ comment.article.comments.count }}
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-tags"></span>&nbsp;&nbsp;{{ comment.article.tag.count }}
                            <span class="pull-right">
                                <span class="glyphicon glyphicon-calendar"></span>&nbsp;&nbsp;{{ comment.article.created|date }}
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <a href="{{ path('app_article_view', {'id': comment.article.id}) }}" class="read_more" data-toggle="tooltip" title="Read more"><span class="glyphicon glyphicon-option-horizontal"></span></a>
                            </span>
                        </p>
                        <br>
                        <p><b>Comment:</b> {{ comment.text }}</p>
                    </div>
                    <hr>
                {% endfor %}
            {% else %}
                <div class="panel-body">
                    <p class="text-center">(No commented articles)</p>
                </div>
            {% endif %}
            <div class="panel-body">
                <a href="{{ path('app_profile_view', {'id': author.id}) }}" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Back</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/profile/likes.html.twig
{% extends 'user/base.html.twig' %}

{% block title %}Symfony Blog - {{ author.firstName }} {{ author.lastName }} - Liked articles{% endblock %}

{% block body %}
    <div class="row">
        {{ include('user/breadcrumb.html.twig', { 'crumb': 'Profile', 'active': 'Liked articles' }) }}
        <div class="panel panel-default panel-article">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-book"></span>&nbsp;&nbsp;Liked articles</h3>
            </div>
            {% if author.likes and author.likes|length > 0 %}
                {% for like in author.likes %}
                    <div class="panel-body">
                        <p><b><a href="{{ path('app_article_view', {'id': like.article.id}) }}">{{ like.article.title }}</a></b></p>
                        <p>{{ like.article.shortText }}</p>
                        <p>
                            <span class="glyphicon glyphicon-heart"></span>&nbsp;&nbsp;{{ like.article.likes.count }}
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-comment"></span>&nbsp;&nbsp;{{ like.article.comments.count }}
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-tags"></span>&nbsp;&nbsp;{{ like.article.tag.count }}
                            <span class="pull-right">
                                <span class="glyphicon glyphicon-calendar"></span>&nbsp;&nbsp;{{ like.article.created|date }}
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <a href="{{ path('app_article_view', {'id': like.article.id}) }}" class="read_more" data-toggle="tooltip" title="Read more"><span class="glyphicon glyphicon-option-horizontal"></span></a>
                            </span>
                        </p>
                    </div>
                    <hr>
                {% endfor %}
            {% else %}
                <div class="panel-body">
                    <p class="text-center">(No liked articles)</p>
                </div>
            {% endif %}
            <div class="panel-body">
                <a href="{{ path('app_profile_view', {'id': author.id}) }}" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Back</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/profile/update.html.twig
{% extends 'user/base.html.twig' %}

{% block title %}Symfony Blog - Edit profile - {{ author.firstName }} {{ author.lastName }}{% endblock %}

{% block body %}
    <div class="row">
        {{ include('user/breadcrumb.html.twig', { 'crumb': 'Edit profile', 'active': author.firstName ~ ' ' ~ author.lastName }) }}
        <div class="panel panel-default panel-article">
            <div class="panel-body">
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <a href="{{ path('app_profile_view', {'id': author.id}) }}" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Back</a>
                <button class="btn btn-default pull-right" type="submit"><span class="glyphicon glyphicon-ok"></span>&nbsp;&nbsp;Update</button>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}